package controller;

import view.LvView;
import au.edu.uts.ap.javafx.*;
import static java.lang.Integer.valueOf;
import javafx.event.*;
import model.*;
import javafx.fxml.*;
import javafx.scene.control.*;
import javafx.scene.text.*;
import javafx.stage.Stage;
import javafx.beans.property.*;
import javafx.beans.value.ObservableValue;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.geometry.Pos;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Pane;
import javafx.scene.shape.*;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;
import static java.lang.Integer.valueOf;

/**
 * The controller for lift.fxml.
 */
public class LiftController extends Controller<Lift> {
    @FXML private Button closeBtn;
    @FXML private Text currentLvTxt;
    @FXML private Text bottomLvTxt;
    @FXML private Text topLvTxt;
    @FXML private Text directionTxt;
    @FXML private Text liftNumber;
    @FXML private ListView<Person> passengerLv;
    @FXML private ListView<Person> queueLv;
    @FXML private TableView<TableColumn> tableLv;
    //@FXML private TableColumn<Lift,String> column;
    //@FXML private ObservableList<TableColumn> columns = FXCollections.observableArrayList();
    //@FXML private LevelView levelView;
    //@FXML private ObservableList<Rectangle> levels;
    //@FXML private LevelView levelView;
    @FXML private LvView levelView ;
    //@FXML private HBox levelbox= new HBox();
    //@FXML private ObservableList<HBox> boxes = FXCollections.observableArrayList();
    
    //@FXML private TableColumn<Lift, String> waitingClm;
    
    

    public final Lift getLift() { return model; }

    @FXML private void initialize() {
        currentLvTxt.textProperty().bind(getLift().levelProperty().asString());
        bottomLvTxt.textProperty().bind(getLift().bottomProperty().asString());
        topLvTxt.textProperty().bind(getLift().topProperty().asString());
        directionTxt.textProperty().bind(getLift().directionText());
        liftNumber.textProperty().bind(getLift().numberProperty().asString());
        //levelView02.bind((ObservableValue<? extends Number>) getLift().getLevelView());
        //levelView.setLevelBox(getLift());
        levelView=getLift().levelView();
    }
    /*
    private void tableView(){
        //create a table view of 1 row, columns = (top-bottom)  observables)
        //connect this table to lift fxml
        //TableView(ObservableList<S> items)
        //For Loop
        
        
            //for(TableColumn column : columns){
                for (int i = getLift().getBottom() ; i<=getLift().getTop(); i++){
                    IntegerProperty level = new SimpleIntegerProperty();
                    level.setValue(i);
                    TableColumn<Lift,String> each = new TableColumn<Lift,String>();
                    each.setCellValueFactory(cellData -> level.asString());
                    columns.add(each);
                    System.out.println(level.get());
                    
                }
           // }
        
            //column.setCellValueFactory(cellData -> cell);
        
    }
    */
    public final int getNumber() {return getLift().getNumber();}
    
    @FXML private void handleClose(ActionEvent event) throws Exception {
        stage.close();
    }

    
}
